config/routes.rb
Translator::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'

  resources :welcome do
    get :help
    get :about
  end
  resources :translations do
    resources :lexems
    resources :syntexes
  end
  resources :reservedkeywords
  resources :reservedsymbols
end

app/models/reservedsymbol.rb
class Reservedsymbol < ActiveRecord::Base

	validates :symbols, presence: true

end

app/controllers/reservedsymbols_controller.rb
class ReservedsymbolsController < ApplicationController
	def new
	end

	def create
		@reservedsymbol = Reservedsymbol.create(reservedsymbol_params)
		render "show"
	end

	def show
		unless @reservedsymbol = Reservedsymbol.where(id: 1).first
			render "new"
		end
	end

	def edit
		@reservedsymbol = Reservedsymbol.where(id: 1).first
	end

	def update
		@reservedsymbol = Reservedsymbol.find(1)
		@reservedsymbol.update_attributes(reservedsymbol_params)
		if @reservedsymbol.errors.empty?
			redirect_to reservedsymbol_path(1)
		else 
			flash.now[:error] = "Поле не может быть пустым!"
			render "edit"
		end
	end

	private

		def reservedsymbol_params
			params.require(:reservedsymbol).permit(:symbols)
		end
end

app/helpers/reservedsymbols_helper.rb
module ReservedsymbolsHelper
end

app/views/reservedsymbols/edit.html.haml
=render partial: "/layouts/header"
.center
	%h1 Редактирование зарезервированных символов
	%h5= flash[:error]
	%h5 Обновите нужную программу, чтобы изменения вступили в силу
	= simple_form_for @reservedsymbol do |f|
		= f.text_area :symbols, size:'40x8'
		%p
		%p
		<button type="submit" class="btn btn-info">Сохранить изменения</button>
		%h4= link_to "Назад", reservedsymbol_path(1)
=render partial: "/layouts/footer" 

app/views/reservedsymbols/new.html.haml
=render partial: "/layouts/header"
.center
	%h1 Создание зарезервированных символов
	= simple_form_for Reservedsymbol.new do |f|
		= f.text_area :symbols, size:'40x8'
		%p
		%p
		<button type="submit" class="btn btn-info">Сохранить</button>
		%h4= link_to "Назад", reservedsymbol_path(1)
=render partial: "/layouts/footer" 

app/views/reservedsymbols/show.html.haml
=render partial: "/layouts/header"
%h1 Зарезервированные символы
.center
	%h2=@reservedsymbol.symbols.gsub(/[0-9\|]/, " ")
%p
.center
	= link_to "Редактировать", edit_reservedsymbol_path(1)
=render partial: "/layouts/footer" 