config/routes.rb
Translator::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'

  resources :welcome do
    get :help
    get :about
  end
  resources :translations do
    resources :lexems
    resources :syntexes
  end
  resources :reservedkeywords
  resources :reservedsymbols
end

app/models/translation.rb
class Translation < ActiveRecord::Base	

	validates :name, :inprogram, presence: true

	has_one :lexem 
	has_one :number 
	has_one :translationsting
	has_one :variable
	has_one :error
	has_one :syntex

end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
	def index
		@translations = Translation.all 
	end

	def show
		unless @translation = Translation.where(id: params[:id]).first
		render_404
		end
	end

	def new
		@translation = Translation.new
	end

	def edit
		@translation = Translation.find(params[:id])
	end

	def create
		@translation = Translation.create(translation_params)
		if @translation.errors.empty?
			redirect_to translation_lexems_path(@translation)
		else 
			flash.now[:error] = "Вы не заполнили обязательные поля!"
			render "new"
		end
	end

	def update
		@translation = Translation.find(params[:id])
		@translation.update_attributes(translation_params)
		if @translation.errors.empty?
			redirect_to edit_translation_lexem_path(id: @translation.id, translation_id: @translation.id)
		else 
			flash.now[:error] = "Вы не заполнили обязательные поля!"
			render "edit"
		end
	end

	def destroy
		@translation = Translation.find(params[:id])
		@lexem = Lexem.where(translation_id: @translation.id).each
		@rule = Syntex.where(translation_id: @translation.id).each
		@translation.destroy
		@lexem.each do |i|
			i.destroy		
		end
		@rule.each do |i|
			i.destroy		
		end
		redirect_to action: "index"
	end

	private

		def translation_params
			params.require(:translation).permit(:name, :inprogram)
		end 
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/edit.html.haml
=render partial: "/layouts/header" 
%h1 Изменить трансляцию
.center
	%h5= flash[:error] 
	=simple_form_for @translation do |f|
		= f.input :name, label: "Название"
		%h2 Исходный код
		= f.text_area :inprogram, size:'40x8'
		%p
		%p
		<button type="submit" class="btn btn-info">Применить изменения</button>
		%h4= link_to "Назад", translation_path
=render partial: "/layouts/footer" 	

app/views/translations/index.html.haml
=render partial: "/layouts/header"
-if @translations.blank?
	%h1 Нет программ
-else
	%h1 Список программ

	%table.table-bordered
		%thead
			%th Название
			%th Обновить трансляцию
			%th Редактировать трансляцию
			%th Удалить трансляцию
		- @translations.each do |t|
			%tbody
				%td= link_to t.name, translation_path(t)
				%td= link_to "Обновить", edit_translation_lexem_path(id: t.id, translation_id: t.id)
				%td= link_to "Редактировать", edit_translation_path(t)
				%td= link_to "Удалить", t, method: :delete, data:{confirm: "Вы уверены?"}
=render partial: "/layouts/footer" 

app/views/translations/new.html.haml
=render partial: "/layouts/header"
%h1 Новая трансляция
.center
	%h5= flash[:error] 
	=simple_form_for @translation do |f|
		= f.input :name, label: "Название"
		%h2 Исходный код
		= f.text_area :inprogram, size:'40x8'
		%p
		%p
		<button type="submit" class="btn btn-info">Транслировать</button>
=render partial: "/layouts/footer"

app/views/translations/show.html.haml
=render partial: "/layouts/header"
%h1= @translation.name
%table.table-bordered
	%thead
		%th Текст программы на языке Милан
		%th Текст программы на языке С
	%tbody
		%td= @translation.inprogram
		%td= @translation.outprogram
%p
.center
	%table
		%td= link_to "Таблица лексем", translation_lexem_path(translation_id: params[:id])
		%td= link_to "Дерево вывода", translation_syntex_path(translation_id: params[:id])
		%td= link_to "Обновить запись", edit_translation_lexem_path(id: @translation.id, translation_id: @translation.id)
		%td= link_to "Редактировать запись", edit_translation_path
		%td= link_to "Удалить запись", @translation, method: :delete, data:{confirm: "Вы уверены?"}
=render partial: "/layouts/footer"