config/routes.rb
Translator::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'

  resources :welcome do
    get :help
    get :about
  end
  resources :translations do
    resources :lexems
    resources :syntexes
  end
  resources :reservedkeywords
  resources :reservedsymbols
end

app/models/reservedkeyword.rb
class Reservedkeyword < ActiveRecord::Base

	validates :keywords, presence: true

end

app/controllers/reservedkeywords_controller.rb
class ReservedkeywordsController < ApplicationController
	def new
	end

	def create
		@reservedkeyword = Reservedkeyword.create(reservedkeyword_params)
		render "show"
	end

	def show
		unless @reservedkeyword = Reservedkeyword.where(id: 1).first
			render "new"
		end
	end

	def edit
		@reservedkeyword = Reservedkeyword.where(id: 1).first
	end

	def update
		@reservedkeyword = Reservedkeyword.find(1)
		@reservedkeyword.update_attributes(reservedkeyword_params)
		if @reservedkeyword.errors.empty?
			redirect_to reservedkeyword_path(1)
		else 
			flash.now[:error] = "Поле не может быть пустым!"
			render "edit"
		end
	end

	private

		def reservedkeyword_params
			params.require(:reservedkeyword).permit(:keywords)
		end 

end

app/helpers/reservedkeywords_helper.rb
module ReservedkeywordsHelper
end

app/views/reservedkeywords/edit.html.haml
=render partial: "/layouts/header"
.center
	%h1 Редактирование ключевых слов
	%h5= flash[:error]
	%h5 Обновите нужную программу, чтобы изменения вступили в силу
	= simple_form_for @reservedkeyword do |f|
		= f.text_area :keywords, size:'40x8'
		%p
		%p
		<button type="submit" class="btn btn-info">Сохранить изменения</button>
		%h4= link_to "Назад", reservedkeyword_path(1)
=render partial: "/layouts/footer"

app/views/reservedkeywords/new.html.haml
=render partial: "/layouts/header"
.center
	%h1 Создание ключевых слов
	= simple_form_for Reservedkeyword.new do |f|
		= f.text_area :keywords, size:'40x8'
		%p
		%p
		<button type="submit" class="btn btn-info">Сохранить</button>
		%h4= link_to "Назад", reservedkeyword_path(1)
=render partial: "/layouts/footer"

app/views/reservedkeywords/show.html.haml
=render partial: "/layouts/header"
%h1 Ключевые слова
.center
	%h2=@reservedkeyword.keywords.gsub(/[0-9\|]/, " ")
%p
.center
	= link_to "Редактировать", edit_reservedkeyword_path(1)
=render partial: "/layouts/footer" 